### ISSUE TITLE
Make this project truly open-source and add build instructions to Readme or Github Wiki

### ISSUE THREAD

**Issue by JeffRockatansky** [Mimieam/TabSorter2#26]
@Mimieam @gitatmax Could you please make sources for this extension public in this repository and give us instructions on how to build it ourselves? It will be good for community contributions (pull requests, possible forks if you abandon it, etc.), quality of code and trustworthiness.

**Comment by JeffRockatansky** [comment]
Btw I do not have any intention of stealing your project, if that's your concern. And you already distribute it as a browser extension, which can be easily reverse-engineered. Opening the source code will only result in benefits for all of us.

**Comment by JeffRockatansky** [comment]
I also would like to contribute something myself as a pull request as I learn React and stuff.

**Comment by gitatmax** [comment]
Hi! I've contributed here but am not directly involved with the project. I agree that it'd be nice if it was more open to some degree, but that is entirely up to @Mimieam

> I don't pretend on the donation money

Could you please elaborate on what you mean on that?

**Comment by JeffRockatansky** [comment]
> Could you please elaborate on what you mean on that?

Edited this line. It was poorly translated, sorry.

Mimieam has a buymeacoffee donation link on extension config options page. So I guess his intention is to make some money on this project.

**Comment by JeffRockatansky** [comment]
@Mimieam No offence, but it strogly looks like you're abandoning this project or can't develop it only by yourself. Let us help you.

**Comment by gitatmax** [comment]
> @Mimieam No offence, but it strogly looks like you're abandoning this project or can't develop it only by yourself. Let us help you.

It's only been 2 months; I've seen developers come back after years before they thought it was okay to add to their work. Give it some time, or roll your own! If you do, I'd love to know about it. :)

**Comment by Mimieam** [comment]
Hi @JeffRockatansky, rest assured that the development of Ts2 has not been abandoned!
Tho it was slowed due to financial resources... in 3 yrs the donation made about $15.. while I'm very grateful for any support at all, I can't make rent on that and with 2020 I had to shift my priorities and try to keep a roof over my head 😬

That being said, the Intent of this repo was mainly to provide a way to reach out with issues and improvements. As it currently stands, there are 2 core parts of the code which are not open source and are the ultimate reason why the code is not available here. I apologize for the inconvenience but until I find a workaround for those Ts2 can't be fully open source :/  

Now I have to say I really like your enthusiasm and tenacity so if you still want to contribute, my [latest](https://github.com/Mimieam/workSpaceLive) extension is fully open source and I sure could use some help there :)

**Comment by Mimieam** [comment]
@gitatmax Thank you for your kind words, I appreciate the support :)

**Comment by JeffRockatansky** [comment]
Why closed?

**Comment by JeffRockatansky** [comment]
Have you managed to release the source code on Github?
